# Generated by Django 4.0.2 on 2022-04-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(default='', upload_to='dp'),
        ),
    ]
